viruses:
  - name: "influenza_a"
    filmarray:
      col_name: "influenza_a"
      values: "DETECTADO"
    other_viruses:
      col_name: "influenzaaporrtpcrvegeneral"
      values: ["positivo"]
      col_subtypes: "virusdetectadosvegeneral"
      original_value: ["positivo"]
      valid_result: TRUE
    label: "A no subtipificado"
    subtypes: ["h1n1", "h1n1_pdm09", "h3n2"]

  - name: "h1n1"
    filmarray:
      col_name: "influenza_a_h1"
      values: "DETECTADO"
    other_viruses:
      col_name: "virusdetectadosvegeneral"
      values: [""]
    label: "H1N1"

  - name: "h1n1_pdm09"
    filmarray:
      col_name: "influenza_a_h1_2009"
      values: "DETECTADO"
    other_viruses:
      col_name: "virusdetectadosvegeneral"
      values: ["h1n1_pdm09", "hn1_pdm09", "pdm09", "a_pdm09", "h1n1pdm09"]
    label: "H1N1 2009"

  - name: "h3n2"
    filmarray:
      col_name: "influenza_a_h3"
      values: "DETECTADO"
    other_viruses:
      col_name: "virusdetectadosvegeneral"
      values: ["a_h3"]
    label: "H3N2"

  - name: "influenza_b"
    filmarray:
      col_name: "influenza_b"
      values: "DETECTADO"
    other_viruses:
      col_name: "influenzabporrtpcrvegeneral"
      values: ["positivo"]
      valid_result: TRUE
    label: "Influenza B"

  - name: "otros_virus"
    filmarray:
      col_name: "rinovirus_enterovirus_humano"
      values: "DETECTADO"
    other_viruses:
      col_name: "virusdetectadosvegeneral"
      values: ["enterovirus", "coronavirus_nl63"]
    label: "Otros Virus"

  - name: "bocavirus"
    filmarray: {}
    other_viruses:
      col_name: "virusdetectadosvegeneral"
      values: ["bocavoirus_hbov", "bocavorus", "bocavirus"]
    label: "Bocavirus"

  - name: "metapneumovirus"
    filmarray:
      col_name: "metapneumovirus_humano"
      values: "DETECTADO"
    other_viruses:
      col_name: "virusdetectadosvegeneral"
      values: ["metapneumovirus", "metaneumovirus"]
    label: "Metapneumovirus"

  - name: "rinovirus"
    filmarray:
      col_name: "rinovirus_enterovirus_humano"
      values: "DETECTADO"
    other_viruses:
      col_name: "virusdetectadosvegeneral"
      values: ["rinovirus", "rhinovirus"]
    label: "Rinovirus"

  - name: "parainfluenza"
    filmarray:
      col_name: ["virus_parainfluenza_1", "virus_parainfluenza_2", "virus_parainfluenza_3", "virus_parainfluenza_4"]
      values: "DETECTADO"
    other_viruses:
      col_name: "virusdetectadosvegeneral"
      values: ["parai"]
    label: "Parainfluenza"

  - name: "vsr"
    filmarray:
      col_name: "virus_sincitial_respiratorio"
      values: "DETECTADO"
    other_viruses:
      col_name: "virussincitialrespiratoriovsrporrtpcrvegeneral"
      values: ["positivo"]
      valid_result: TRUE
    label: "VSR"

  - name: "adenovirus"
    filmarray:
      col_name: ["adenovirus"]
      values: "DETECTADO"
    other_viruses:
      col_name: "adenovirusadvporrtpcrvegeneral"
      values: ["positivo"]
      valid_result: TRUE
    label: "Adenovirus"
